name = "cloud-mail-vps"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[dev]
ip = "0.0.0.0"
port = 8000
local_protocol = "http"

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "local-email"

[[kv_namespaces]]
binding = "kv"
id = "local-kv"

[[r2_buckets]]
binding = "r2"
bucket_name = "email"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
orm_log = false
domain = []
admin = "superadmin@jhupo.com"
jwt_secret = "change_me_super_secret"

[build]
command = "npm --prefix ../mail-vue install --legacy-peer-deps && npm --prefix ../mail-vue run build"
